### ISSUE TITLE
Feature Request: Adding table of contents of CGP book to PDF index

### ISSUE THREAD

**Issue by nose-gnome** [Stefanuk12/cgp-rip#2]
Add an index to created PDF consisting of the table of contents from the online version of the book

**Comment by Stefanuk12** [comment]
This used to be a feature when the SVG support wasn't added. This doesn't exist in the current version because of limitations with puppeteer and pdf-merger-js.

IIRC, they don't have support for adding ToC. A solution to this is to use another PDF parser in order to add them in like jsPDF.

Functions to get details like the page names can be found in Utilities or Book. However, I'm not working on this project anymore so I won't be adding anything or updating unless I need to use it personally.

You're always welcome to create a fork and submit a pull request though.
